name: optional
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 4.15.0
  firebase_core: 2.25.4
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.13.0
  google_sign_in: ^6.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  image_picker: ^1.0.7 
  # shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  http: ^0.13.6
  url_launcher: ^6.1.7  # For opening links in browser
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  firebase_messaging: ^14.7.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/optional.png" # Path to your app icon

flutter:
  uses-material-design: true

  # Uncomment and add assets here when needed
  assets:
  - assets/images/signup.jpg
  - assets/google-logo.png
  - assets/apple.png
  - assets/facebook.jpg

  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic

    - family: OpenSauce
      fonts:
        - asset: fonts/open-sauce.sans-black.ttf
